import type { Metadata } from "next";
import { urbanist } from "@/fonts";
import "./globals.css";
import { cn } from "@/lib/utils";
import LeftContainer from "@/components/left-container";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full scrollbar-none",
        "antialiased",
        urbanist.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col md:flex-row">
        <LeftContainer />
        {children}
      </body>
    </html>
  );
}
